name: Deploy CloudFormation Stack

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # Required for OIDC
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::292025927628:role/github-action-role
          aws-region: us-east-1

      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file s3-bucket.yaml \
            --stack-name my-stack \
            --capabilities CAPABILITY_IAM \
            --parameter-overrides Environment=production

      - name: Get Stack Outputs
        run: |
          aws cloudformation describe-stacks \
            --stack-name my-stack \
            --query 'Stacks[0].Outputs'
